# config.py
config = {
    'contacts': {
        'mechanic': '328-555-0153',
        'mors_mutual': '611-555-0149',
        'pegasus': '328-555-0122',
        'merryweather': '273-555-0120',
        'assistant': '346-555-0137',
        'lester': '346-555-0102',
        'pavel':'611-555-0196',
        'paige':'611-555-0192',
        'emergency':'911',
    },
    'waits': {
        "very_short": 0.05,
        "short": 0.15,
        "medium": 0.3,
        "long": 0.7,
        "very_long": 1,
        "phone_open": 0.5,
    },
    'interaction_menu': {
        'level01': {
            'CEO': {
                'Hire Associates': [],
                "Management": [],
                "VIP Work": [],
                'VIP Challenges': [],
                'CEO Abilities': {
                    'Request Luxury Helicopter': [],
                    'Drop Bull Shakr': [],
                    'Drop Ammo': [],
                    'Drop Armor': [],
                    'Ghost Organization': [],
                    'Bribe Authorities': [],
                    'Spectate Associates': [],
                },
                'CEO Vehicles': {
                    'Turreted Limo': [],
                    'Baller LE LWB': [],
                    'XLS': [],
                    'BeeJay XL': [],
                    'Buzzard': [],
                    'Cognoscenti': [],
                    'Brickade': [],
                    'Rumpo Custom': [],
                    'Dinghy': [],
                    'Volatus': [],
                    'Schafter LWB': [],
                    'Washington': [],
                    'Stretch': [],
                    'Patriot': [],
                    'Super Diamond': [],
                    'SuperVolito': [],
                    'Sanchez': [],
                    'Duneloader': [],
                    'Budhi': [],
                    'Havok': [],
                },
                'Retire': []                
            },
            'Register as Boss': [],
            'Manage Vehicles': {
                'Request Personal Vehicle': [],
                'Request Personal Aircraft': [], 
                'Request Special Vehicle': [],
                'Bail Office Transporter': [],
                'Remote Control Vehicles': [],
                'Return Personal Vehicle to Storage': [],
                'Vehicle Prefereces': [],
            },
            'Service Vehicles': [
                'Galaxy Super Yacht',
                'Mobile Operations Center',
                'Avenger',
                'Terrorbyte',
                'Kosatka',
                'Acid Lab',
            ],
            'Health and Ammo': {
                'Ammo': [],
                'Body Armor': {
                    'Super Light Armor': [],
                    'Light Armor': [],
                    'Standard Armor': [],
                    'Heavy Armor': [],
                    'Super Heavy Armor': [],
                    'Equip Armor': [],
                    'Auto Equip Armor': []
                },
                'Snacks': {
                    'P&Q’s': [],
                    'EgoChaser': [],
                    'Meteorite': [],
                    'eCola': [],
                    'Pisswasser': [],
                    'Smokes': [],
                    'Sprunk': [], 
                }
            },
            'Appearance': {
                'Change Appearance': [],
                'Accessories': [],
                'Parachute': [],
                'Outfit': [],
                'Stunt Racing Outfit': [],
                'Bike Helmet': [],
                'Helmet Visor': [],
                'Auto Equip Bike Helmet': [],
                'Auto Equip Aircraft Helmet': [],
                'Illuminated Clothing': [],
                'Hood': [],
                'Jacket': [],
                'Action': [],
                'Dance Style': [],
                'Dance Partner': [],
                'Expression': [],
                'Expression (Race)': [],
                'Expression(Deathmatch)': [],
                'Walk Style': [],
            },
            'Challenges': [],
                'Daily Challenges': [],
                'Weekly Challenges': [],            
        }
    }
}
